language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "pypy"
install:
    - easy_install -U setuptools
    - pip install ipython==1.2.1
    - pip install ipythonblocks
    - pip install .
    - pip install pytest-cov
    - pip install coveralls
script:
    - py.test --cov brewer2mpl --cov-report term-missing
after_success:
    - coveralls
