language: python
sudo: false
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "pypy"
env:
    - IPYTHON_INSTALL='pip install ipython'
matrix:
    include:
        - python: "2.6"
          env: IPYTHON_INSTALL='pip install ipython==1.2.1'
install:
    - easy_install -U setuptools
    - $IPYTHON_INSTALL
    - pip install ipythonblocks
    - pip install .
    - pip install pytest-cov
    - pip install coveralls
script:
    - py.test --cov palettable --cov-report term-missing
after_success:
    - coveralls
